apiVersion: v1
kind: Service
metadata:
  name: donation-service
  namespace: services
spec:
  type: NodePort
  selector:
    app: donation-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30081