{
 "title": "Esperanca Solidaria - Microsservicos",
 "tags": [
  "esperanca-solidaria",
  "zabbix"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Process CPU Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "group": { "filter": "Esperanca Solidaria" },
     "host": { "filter": "/.*/" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "item": { "filter": "Process CPU Seconds" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     }
    }
   ]
  },
  {
   "title": "Threads Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "group": { "filter": "Esperanca Solidaria" },
     "host": { "filter": "/.*/" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "item": { "filter": "Threads Count" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     }
    }
   ]
  },
  {
   "title": "HTTP Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "group": { "filter": "Esperanca Solidaria" },
     "host": { "filter": "/.*/" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "item": { "filter": "HTTP Total Requests" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     }
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "group": { "filter": "Esperanca Solidaria" },
     "host": { "filter": "/.*/" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "item": { "filter": "Memory Usage" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     }
    }
   ]
  }
 ]
}