apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: conexao-solidaria
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: admin
  RABBITMQ_DEFAULT_PASS: 50L1D4R10@pass

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: conexao-solidaria
data:
  RABBITMQ_ERLANG_COOKIE: "secret-cookie"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  namespace: conexao-solidaria
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: conexao-solidaria
spec:
  selector:
    app: rabbitmq

  ports:
    - name: amqp
      port: 5672
      targetPort: 5672

    - name: management
      port: 15672
      targetPort: 15672

  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: conexao-solidaria
spec:
  replicas: 1

  selector:
    matchLabels:
      app: rabbitmq

  template:
    metadata:
      labels:
        app: rabbitmq

    spec:
      containers:
        - name: rabbitmq

          image: rabbitmq:3-management

          ports:
            - containerPort: 5672
            - containerPort: 15672

          envFrom:
            - secretRef:
                name: rabbitmq-secret

            - configMapRef:
                name: rabbitmq-config

          volumeMounts:
            - name: rabbitmq-storage
              mountPath: /var/lib/rabbitmq

      volumes:
        - name: rabbitmq-storage
          persistentVolumeClaim:
            claimName: rabbitmq-pvc