apiVersion: v1
kind: Secret
metadata:
  name: services-secrets
  namespace: services
type: Opaque
stringData:
  rabbitMQDefaultUser: "EsperancaAdmin"
  rabbitMQDefaultPass: "EsperancaSolidaria@123"
  rabbitMQDefaultVHost: "/"
  rabbitMQDefaultHost: "localhost"
  connectionString: "mongodb://host.docker.internal:27017"
  jwtKey: "32nklfdsknsdknf332032505702da5ff3179e1safasfdsfbajwqob0087cf0cfdd1c72352390ujrfsdoklmfgdkdsnla"
  expiration: "15"