apiVersion: v1
kind: Secret
metadata:
  name: services-secrets
  namespace: services
type: Opaque
stringData:
  rabbitMQDefaultUser: "EsperancaAdmin"
  rabbitMQDefaultPass: "EsperancaSolidaria@123"
  rabbitMQDefaultVHost: "/"
  rabbitMQDefaultHost: "localhost"
  connectionString: "mongodb+srv://fiap-god-user:X2LT1YZ3Gykx0MsO@fiap-tech-challenge.dkbjuoa.mongodb.net/fiap-demo?appName=FIAP-Tech-Challenge"
  jwtKey: "32nklfdsknsdknf332032505702da5ff3179e1safasfdsfbajwqob0087cf0cfdd1c72352390ujrfsdoklmfgdkdsnla"
  expiration: "15"