apiVersion: v1
kind: Secret
metadata:
  name: user-api-secrets
  namespace: services
type: Opaque
stringData:
  bootstrapAdminCpf: "99251344043"
  bootstrapAdminEmail: "admin@admin.com"
  bootstrapAdminPassword: "Admin@123"