name: UserService CI

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'src/UserService/**'

  push:
    branches:
      - develop
    paths:
      - 'src/UserService/**'

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: UserService

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore UserService.sln

      - name: Build
        run: |
          dotnet build \
          UserService.sln \
          --configuration Release \
          --no-restore

      - name: Run Tests
        run: |
          dotnet test \
          UserService.sln \
          --configuration Release \
          --no-build \
          --collect:"XPlat Code Coverage"

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: user-service-test-results
          path: |
            UserService/tests/**/TestResults

      - name: Docker Build Validation
        run: |
          docker build \
          -t user-service:ci \
          .

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: user-service-build
          path: |
            UserService/src/**/bin/Release